# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: MSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArchitecture: 'x64'
    msbuildArguments: >-
        -p:AppxBundle=Always
        -p:AppxBundlePlatforms="$(buildPlatform)"
        -p:AppxPackageDir="$(Build.ArtifactStagingDirectory)\\AppxPackages\\"
        -p:AppxSymbolPackageEnabled=false
        -p:UapAppxPackageBuildMode=SideLoadOnly


- script: echo %Action%%BuildVersion%
  displayName: 'Update build number to SemVer'
  env:
    Action: '##vso[build.updatebuildnumber]'
    BuildVersion: '$(GitVersion.FullSemVer)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: UWP installer'
  inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)\AppxPackages\
      ArtifactName: Installer