# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
- develop
- master
- release/*

variables:
  BuildPlatform: 'x64'
  BuildConfiguration: 'release'
  system.debug: false

jobs:
- job: BuildTestDeploy
  displayName: 'Build, Test and Deploy'
  cancelTimeoutInMinutes: 1
  pool:
    vmImage: windows-2022
    demands:
    - DotNetFramework
    - msbuild
    - vstest
  steps:
    - checkout: self
      clean: true
      lfs: true
      persistCredentials: true
      fetchTags: false
      
    - task: NuGetToolInstaller@1
      displayName: 'Update NuGet'
      inputs:
        checkLatest: true
  
    - task: NuGetCommand@2
      displayName: Restore NuGet packages
      inputs:
        solution: 'WinUI_VersionCheck.sln'
        selectOrConfig: config
        nugetConfigPath: nuget.config
  
    - task: VSBuild@1
      inputs:
        solution: 'WinUI_VersionCheck.sln'
        vsVersion: '17.0'
        msbuildArgs: >-
          -p:AppxBundle=Always
          -p:UapAppxPackageBuildMode=CI
          -p:AppxPackageDir="$(Build.ArtifactStagingDirectory)\\AppxPackages\\"
          -p:AppxBundlePlatforms=$(BuildPlatform)
          -p:AppxSymbolPackageEnabled=false
          -p:GenerateAppxPackageOnBuild=True
        platform: 'x64'
        configuration: 'release'
        clean: true
        restoreNugetPackages: true
        msbuildArchitecture: 'x64'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: UWP installer'
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)\AppxPackages\
        ArtifactName: Installer